name: 构建APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: 设置 JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: 授予执行运行gradlew权限
        run: chmod +x gradlew
      - name: 使用Gradle构建
        run: ./gradlew build
        #签名安装包
      - uses: kevin-david/zipalign-sign-android-release@v1.1
        name: 签名APK文件
        #  用于访问动作输出的ID。
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          zipAlign: true
        env:
          # 覆盖默认的构建工具版本（32.0.0）-- 可选
          BUILD_TOOLS_VERSION: "32.0.0"

      # 签名发布文件输出的示例用法 -- 无需
      - uses: actions/upload-artifact@v2
        with:
          name: 安装包
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

#          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Releasing using Hub
        uses: VladDaniliuk/action-release-releaseapk@master
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          VERSION_VARIABLE: versionName
          APP_FILE: ./app/build.gradle
          APP_FOLDER: ${{steps.sign_app.outputs.signedReleaseFile}}
          #./app/release/app.apk
          CHANGELOG_FILE: ./CHANGELOG.md
          RELEASE_TITLE: New Build
          NAME_VARIABLE: app-release.apk