name: 构建APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: 设置 JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute 运行 gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: 上传apk
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: 安装包
          artifacts: ${{ github.workspace }}/app/build/outputs/apk/release/*.apk